version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
  backend-rest-api:
    build: ./backend-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  backend:
    build: ./backend
    ports:
      - "8081:8081"
    depends_on:
      - backend-rest-api
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend